#ID:229668
#Nombre:santiago lopez angel
name: examen-cadena-frio-postgres

services:
  postgres:
    image: postgres:18
    container_name: postgres-cadena-frio
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_cadena_frio_data:/var/lib/postgresql
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

volumes:
  postgres_cadena_frio_data: